### ISSUE TITLE
Read + Seek from object?

### ISSUE THREAD

**Issue by curoli** [ThouCheese/cloud-storage-rs#112]
Hello,

I need a Read + Seek for a GCS object. Is there a way to get this? Thanks!

Best, Oliver

**Comment by ThouCheese** [comment]
This is currently not implemented in cloud-storage, however, you can download the contents of a file to a vec and then wrap that in a cursor:

```rust
let bytes = Object::download("my_bucket", "path/to/my/file.png").await?;
let cursor = std::io::Cursor::new(bytes);
// now cursor implements Read and Seek
```
