### ISSUE TITLE
BucketClient::list Returns Error on successful response

### ISSUE THREAD

**Issue by e-rhodes** [ThouCheese/cloud-storage-rs#115]
`BucketClient::list` appears to always return an error:
```
[src/main.rs:6] client.bucket().list().await = Err(
    Reqwest(
        reqwest::Error {
            kind: Decode,
            source: Error("data did not match any variant of untagged enum GoogleResponse", line: 0, column: 0),
        },
    ),
)
```

It also seems to have some `dbg!()`s left in--it runs the query twice just to debug print it (which is how we can see that the response successfully gets the buckets).

**Comment by e-rhodes** [comment]
Looks like this is because I've got a bucket with a `cors` that includes only the `method` and `origin` fields, for whatever reason. This can be fixed by changing the `max_age_seconds` field on `Cors` to an `Option<i32>` and adding the `#[serde(default)]` annotation on all fields.

**Comment by ThouCheese** [comment]
Merged! Thanks a lot!
