### ISSUE TITLE
Wrong environment variable being used?

### ISSUE THREAD

**Issue by akrantz01** [ThouCheese/cloud-storage-rs#12]
I noticed that you're using `SERVICE_ACCOUNT` instead of `GOOGLE_APPLICATION_CREDENTIALS` for the environment variable, is there any particular reason for this? I think `GOOGLE_APPLICATION_CREDENTIALS` should probably be used since it how GCP services will provide the service account file.

**Comment by ThouCheese** [comment]
We could be more consistent with Google's client libraries checking for `GOOGLE_APPLICATION_CREDENTIALS`, and we can just check for both to prevent making a breaking change. I think this is a good addition.

**Comment by ThouCheese** [comment]
This is now on crates.io as version 0.4.2.
