### ISSUE TITLE
Is this the right repo for cloud-storage-rs?

### ISSUE THREAD

**Issue by xanderjakeq** [ThouCheese/cloud-storage-rs#14]
This repo is linked from this [crate](https://crates.io/crates/cloud-storage-rs).

I want to know if this is correct since the crate version on crate.io and on the readme is different... 

Thanks.

**Comment by ThouCheese** [comment]
Hey, this is the correct repo! I renamed the library to [cloud-storage](https://docs.rs/cloud-storage) after I got the feedback that the -rs prefix was unnecessary on crates.io. I thought I updated the old version to mention this, but it clearly didn't work :). I'll see if I can't fix the old version.

**Comment by ThouCheese** [comment]
I updated the code in [the old version](https://crates.io/crates/cloud-storage-rs) one last time and added a message to the documentation with a link to the new version. I'm not going to remove the old version since that may break peoples build process.
