### ISSUE TITLE
Issue with permissions

### ISSUE THREAD

**Issue by Yuhanun** [ThouCheese/cloud-storage-rs#17]
Hello,

I'm using this library for work to read grom google cloud storage, however I'm getting a permission error.

I'm assuming this: 
```
Authorization can be granted using the SERVICE_ACCOUNT environment variable, which should contain path to the service-account-*******.json file that contains the Google credentials. The service account requires the permission devstorage.full_control. This is not strictly necessary, so if you need this fixed, let me know!
```

Has something to do with it?

```
     Running `target\debug\something.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other("got error response from Google: something@something.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket.")', src\main.rs:5:18

```

Would love to see this fixed as I definitely do have read permissions + file create + write permissions, just no full access.

**Comment by ThouCheese** [comment]
Hi! If you have read permissions to a specific bucket, that does not mean you are allowed to retrieve a list of all buckets. Are you sure that you have got the permissions right?

**Comment by ThouCheese** [comment]
I'm closing this issues since there has been over a month without activity.
