### ISSUE TITLE
Download Url results in permissions error

### ISSUE THREAD

**Issue by bodymindarts** [ThouCheese/cloud-storage-rs#33]
When accessing a download url for an object that was successfully stored I'm seeing this:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.
</Details>
</Error>
```

Even though I have given the account `roles/storage.objectAdmin` access to the bucket:

```
resource google_storage_bucket_iam_member "artifacts-admin" {
  bucket = google_storage_bucket.artifacts.name
  role   = "roles/storage.objectAdmin"
  member = "serviceAccount:${google_service_account.artifacts-service-account.email}"
}
```

Any idea what permission is missing here?

Update:
This is an example of the URL that was created:
```
https://storage.googleapis.com/testflight-mn-artifacts/dev-credit-notes/masht.pdf?X-Goog-Algorithm=GOOG4-RSA-SHA256\u0026X-Goog-Credential=testflight-artifacts-account%40misthos-network.iam.gserviceaccount.com%2F20200826%2Fhenk%2Fstorage%2Fgoog4_request\u0026X-Goog-Date=20200826T113518Z\u0026X-Goog-Expires=600\u0026X-Goog-SignedHeaders=host\u0026X-Goog-Signature=4a89db80bf1876d80b45b85b8a37519adb46fd66cbc5747ada3a0b47e9ca65a02029bbac0e5c4f844e30af3c6ed2989660709ce98a2b2b890a34a99b66d325f443d2c482460a2da9e09d1b130db70239dd3f8a81ac664770a2749ad7351b3fc884bcec57a0bebc7ad96bff44273f87a68c4783508ae44428e2651cdd846cfbbe997999df107463b49b2c9d0310b23b4588ae4f2c36b582bbaef5d773ca176a2c205195f9a46587ce65704c850f50dc1a0f6eb94119dba952266b2173247c84848742f169cc83cda68d07c5f895b66ea1ec2fbc858cd145f02be140ae0a262f7767b10be21e77c7ba64331b683cee78cffd4e17c6bdf4e5c3088e46e982616f17
```

I'm wondering if the html escaping (eg `\u0026`) plays a role.

**Comment by bodymindarts** [comment]
Yes its the escaping that is the issue...

**Comment by ThouCheese** [comment]
Hi, so just checking, you were accidentally escaping the url returned by `cloud-storage` and it is not a issue with the library itself?

**Comment by bodymindarts** [comment]
Yes I was getting the url using `grpcurl` talking to a service served via [`tonic`](https://docs.rs/tonic/0.3.1/tonic/) and the returned value was escaped. But a printout in the logs of the service showing the url as it was returned from the library _didn't_ contain any escaping so it must be introduced somewhere else in the stack.

**Comment by ThouCheese** [comment]
Alright brilliant, good luck hunting the bug :)
