### ISSUE TITLE
Return `content-length` header with download stream

### ISSUE THREAD

**Issue by nhynes** [ThouCheese/cloud-storage-rs#36]
`download_streamed` would ideally return the `content-length` header (or be a stream with an accurate `size_hint()`) to obviate an unnecessary extra request to fetch the object `size`.

**Comment by ThouCheese** [comment]
I started implementing this. I think it requires that I construct my own struct that implements futures::Stream, lets call it `SizedByteStream`, which wraps the stream that is returned by Reqwest but offers a different size_hint. To implement Stream, I need to implement the function:
```rust
fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
```
To hand the poll_next implementation off to the wrapped stream, I need to create a Pin to a field of the pinned SizedByteStream. This is explained [here](https://doc.rust-lang.org/stable/std/pin/index.html#pinning-is-structural-for-field), and as you can see it requires unsafe code. I'm not super excited about lifting the `#![forbid(unsafe_code)]` lint from the crate. Do you see a way around this?

**Comment by ThouCheese** [comment]
Also come to think of it, `content-length` specifies the size of the file in bytes, but the iterator returned by `Response::bytes_stream` is an iterator over larger chunks of bytes. It wouldn't suffice to set the `size_hint` of the iterator to `content-length`, because `size_hint` describes the number of elements that the iterator will produce.

**Comment by ThouCheese** [comment]
On my way to publish this I ran ran the tests and the test `object::tests::download_streamed` fail. It only returns the first byte of the file. Notably, `download_streamed_large` passes so there is something weird going on tat requires a bit more investigation before we can release a new version of `cloud-storage`.

**Comment by nhynes** [comment]
Huh, that's weird. I can take a look at this today. What's up with CI, though? Is it possible to provision that with the required secrets, or should I set up my own test bucket?

**Comment by nhynes** [comment]
This works fine on my machine:
```rust
use cloud_storage::Object;
use futures::TryStreamExt as _;

const BUCKET: &str = "cloud-storage-test-bucket";
const FILENAME: &str = "test.txt";
const FILE: &[u8] = b"lorem ipsum dolor sit amet";

#[tokio::main]
async fn main() {
    Object::create(BUCKET, FILE.to_vec(), FILENAME, "text/plain")
        .await
        .unwrap();

    let dl_stream = Object::download_streamed(BUCKET, FILENAME).await.unwrap();
    let dl_file = dl_stream.try_collect::<Vec<_>>().await.unwrap();
    assert_eq!(dl_file, FILE);
}
~
```
I suspect that the test case is encountering an error.

**Comment by ThouCheese** [comment]
The CI is a failed experiment sadly. I wanted all pull requests to be tested, so I created a new GCS project with limited billing to protect against malicious DOS attacks. Sadly however, Github doesn't allow you to opt in to having secrets accessible in public pull request, which I guess makes sense.

About the test: I'm iterating over an option aren't I? Hahaha I'll fix it right away.

**Comment by nhynes** [comment]
> Gthub doesn't allow you to opt in to having secrets accessible in public pull request

You're able to do that now. It's called the [pull_request_target](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target) event.
