### ISSUE TITLE
Consider making _sync methods use BasicScheduler

### ISSUE THREAD

**Issue by nhynes** [ThouCheese/cloud-storage-rs#48]
The `#[tokio::main]` attr attached to all `_sync` methods spawns a multi-threaded runtime, which can impact performance of heavy users of those APIs.
Although I'd recommend removing the `_sync` methods entirely to make explicit the overhead of using `_sync`, it can be lessened somewhat by making a wrapper method that uses the [basic scheduler](https://docs.rs/tokio/0.2.22/tokio/runtime/index.html#basic-scheduler), which is what [reqwest does](https://docs.rs/reqwest/0.10.8/src/reqwest/blocking/client.rs.html#724).

**Comment by ThouCheese** [comment]
This seems reasonable, a multithreaded server is indeed not necessary to transform an async method into a sync one.

**Comment by ThouCheese** [comment]
This could work nicely with migrating `cloud-storage` to a client based approach, where the sync version would store a Tokio runtime in itself to make sure that it needs to be built only once.

**Comment by ThouCheese** [comment]
Resolved by #51.
