### ISSUE TITLE
Refactor the library into a client to remove globals

### ISSUE THREAD

**Issue by nhynes** [ThouCheese/cloud-storage-rs#49]
In addition to making the code hard to reason about, having globals makes it difficult to use multiple instances of things at a time like multiple service accounts, multiple tokio runtimes (when dealing with sync code), and concurrent tests.

Refactoring this library into a `Client` with `Object` and `Bucket` types with more than static methods would be ideal. A modest rewrite would be nice.

**Comment by ThouCheese** [comment]
I'm curious to see what you would consider the best API here. We can do something along the lines of `client.read_objejct("object_id")` or `client.object.read("object_id")` or `Object::read(&client, "object_id")`, all of which are valid patterns.

**Comment by ThouCheese** [comment]
I think the latter one would have my preference. Despite not being the most concise, it makes sure that there is no `Client` type with a hundred methods.

**Comment by ThouCheese** [comment]
Resolved by #51.
