### ISSUE TITLE
create_streamed should take Stream<Item = u8> to be consistent with download_streamed

### ISSUE THREAD

**Issue by nhynes** [ThouCheese/cloud-storage-rs#50]
but the whole thing still feels weird since basically every other library takes `Item=Bytes`. Especially interop with [reqwest::wrap_stream](https://docs.rs/reqwest/0.10.8/reqwest/struct.Body.html#method.wrap_stream). I think that the `Download` with `fn size` and keeping `Item=Bytes` was actually the correct approach.

**Comment by ThouCheese** [comment]
I am hesitant to include `Bytes` in the public API since it is essentially leaking an implementation details from `reqwest` to the caller. Can you provide a clear argument why it is better to expose `Bytes`?
