### ISSUE TITLE
cloud-storage is a little noisy.

### ISSUE THREAD

**Issue by chaaz** [ThouCheese/cloud-storage-rs#67]
(reported on 0.8.3) Using `println!` and `dbg!` macros in `src/resources/object.rs` spit out a bunch of stuff to stdout that makes it difficult to focus on my app. Would it be possible to suppress this, or use the `log`/`env_logger` crates (or similar) to put this output in its own channel?

**Comment by chaaz** [comment]
Example fix is included in https://github.com/ThouCheese/cloud-storage-rs/pull/68

**Comment by ThouCheese** [comment]
This is definitely an oversight. I will release a new version that doesn't print anything to stdout.
