### ISSUE TITLE
Sync object list method returning an async Stream

### ISSUE THREAD

**Issue by Elykz** [ThouCheese/cloud-storage-rs#71]
Im not sure if im missing something, but the sync ObjectClient list method seems to return an async Stream.

Changes from 0.8.4 to 0.9.0

https://docs.rs/cloud-storage/0.8.4/cloud_storage/struct.Object.html#method.list_sync :
```s
pub fn list_sync(
    bucket: &str,
    list_request: ListRequest
) -> Result<Vec<ObjectList>, Error>
```
was transformed to:

https://docs.rs/cloud-storage/0.9.0/cloud_storage/sync/struct.ObjectClient.html#method.list
```s
pub fn list(
    &self,
    bucket: &'a str,
    list_request: ListRequest
) -> Result<impl Stream<Item = Result<ObjectList>> + 'a>
```
Is this intentional ? Shouldn't this method return a  `Result<Vec<ObjectList>, Error>` as its global-client counterpart ?

**Comment by ThouCheese** [comment]
Yeah that is a mistake, I'll get a fix out!

**Comment by ThouCheese** [comment]
`0.10` is now out, since this is a breaking change.
