### ISSUE TITLE
ObjectAccessControl fails on objects with slashes in their name

### ISSUE THREAD

**Issue by jisqyv** [ThouCheese/cloud-storage-rs#74]
Slashes in the object name need to be URL encoded. The work around I have done is to do that encoding prior to calling ObjectAccessControl. I.E:

```rust
let filename = "foo/bar"
Object::create("bucket", content, filename).await?;
let filename = filename.replace("/", "%2F");
ObjectAccessControl::create("bucket", &filename, &acl).await?;
```

**Comment by ThouCheese** [comment]
Thanks for reporting this. I'll try to get a change out soon and release a new version. Fixing this will require a breaking change I think, since your previous code will no longer work.

**Comment by jisqyv** [comment]
Don't worry about breaking my code, I'll fix it. Thanks for responding so quickly.

**Comment by ThouCheese** [comment]
I have released a patch, I think your issue should be fixed. Can you confirm this?

**Comment by ThouCheese** [comment]
I assume it worked and will close the issue.

**Comment by jisqyv** [comment]
@ThouCheese Sorry. I didn't see your change until now. I'll test it out, though from looking over the code, I'm pretty confident that you have the correct fix. Thanks again!

**Comment by ThouCheese** [comment]
No worries, happy to hear that it seems fixed
