### ISSUE TITLE
Sync ObjectClient create_streamed loading whole file into ram

### ISSUE THREAD

**Issue by Elykz** [ThouCheese/cloud-storage-rs#80]
The behaviour of create_streamed method for the sync ObjectClient does not conforms to its description:

From https://docs.rs/cloud-storage/0.10.2/src/cloud_storage/sync/object.rs.html

```s
     /// Create a new object. This works in the same way as `ObjectClient::create`, except it does not need
    /// to load the entire file in ram.
    pub fn create_streamed<R>(
        &self,
        bucket: &str,
        mut file: R,
        length: impl Into<Option<u64>>,
        filename: &str,
        mime_type: &str,
    ) -> crate::Result<Object>
    where
        R: std::io::Read + Send + 'static,
    {
        let mut buffer = Vec::new();
        file.read_to_end(&mut buffer)
            .map_err(|e| crate::Error::Other(e.to_string()))?;
```

While the function descriptions says it does not need to load the whole file into memory, the method
starts by loading the whole file into a buffer. It leads to out-of-me.mory errors when trying to upload files that cannot fit into memory.

**Comment by ThouCheese** [comment]
Right that is a bit weird. Will fix!

**Comment by ThouCheese** [comment]
Hi @Elykz, sorry for the delay, can you check if #89 fixes the issue for you?

**Comment by Elykz** [comment]
Awesome, the fix seems to work fine for me. I could send a 32 GB file with extremely low memory usage (was going out of memory before)
👍👍
