### ISSUE TITLE
Please add optional headers for calls

### ISSUE THREAD

**Issue by jrconlin** [ThouCheese/cloud-storage-rs#83]
There are times when we would like to [specify additional headers](https://cloud.google.com/storage/docs/generations-preconditions#_Preconditions) when calling `create` or similar functions. 

It would be nice to possibly have a separate set of methods that include this ability as a "mix-in".

**Comment by jrconlin** [comment]
Ah, I may be using an old version, since `ObjectPrecondition` now exists. Thanks!

**Comment by pjenvey** [comment]
`ObjectPrecondition` is only for use by a `compose` request, it doesn't enable e.g. enabling a precondition on a `create` request.

This issue is a duplicate of #40 however.
